name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter==5.2.2
          pip install PyPDF2==3.0.1
          pip install pillow==10.2.0
          pip install pyinstaller==6.3.0
      
      - name: Create icon
        run: python pdf_icon.py
      
      - name: Build with PyInstaller
        run: |
          pyinstaller --name="PDF页面顺序反转工具" --windowed --onefile --icon=pdf_reverser.png --add-data="pdf_reverser.png;." --hidden-import=customtkinter --hidden-import=tkinter --hidden-import=PIL --hidden-import=PIL._tkinter_finder --collect-all=customtkinter reverse_pdf_gui.py
      
      - name: Package release
        run: |
          mkdir PDF页面顺序反转工具
          mkdir PDF页面顺序反转工具\程序
          copy dist\PDF页面顺序反转工具.exe PDF页面顺序反转工具\程序\
          copy pdf_reverser.png PDF页面顺序反转工具\程序\
          echo PDF页面顺序反转工具 v1.0 > PDF页面顺序反转工具\使用说明.txt
          echo. >> PDF页面顺序反转工具\使用说明.txt
          echo 功能说明： >> PDF页面顺序反转工具\使用说明.txt
          echo 将PDF文件的页面顺序反转，从最后一页到第一页重新排序。 >> PDF页面顺序反转工具\使用说明.txt
          echo. >> PDF页面顺序反转工具\使用说明.txt
          echo 使用方法： >> PDF页面顺序反转工具\使用说明.txt
          echo 1. 运行 程序\PDF页面顺序反转工具.exe >> PDF页面顺序反转工具\使用说明.txt
          echo 2. 点击"浏览"选择要处理的PDF文件 >> PDF页面顺序反转工具\使用说明.txt
          echo 3. 点击"开始转换" >> PDF页面顺序反转工具\使用说明.txt
          echo 4. 等待处理完成 >> PDF页面顺序反转工具\使用说明.txt
          echo. >> PDF页面顺序反转工具\使用说明.txt
          echo 注意事项： >> PDF页面顺序反转工具\使用说明.txt
          echo - 原文件不会被修改 >> PDF页面顺序反转工具\使用说明.txt
          echo - 新文件会保存在原文件相同目录下 >> PDF页面顺序反转工具\使用说明.txt
          echo - 新文件名格式：原文件名_reversed.pdf >> PDF页面顺序反转工具\使用说明.txt
      
      - name: Create ZIP archive
        run: Compress-Archive -Path PDF页面顺序反转工具 -DestinationPath PDF页面顺序反转工具.zip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF页面顺序反转工具
          path: PDF页面顺序反转工具.zip
      
      - name: Create Release
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: PDF页面顺序反转工具.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}