name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Generate icon
      run: python pdf_icon.py
    
    - name: Build executable
      run: |
        pyinstaller --name="PDF页面顺序反转工具" `
                   --windowed `
                   --onefile `
                   --icon=pdf_reverser.png `
                   --add-data="pdf_reverser.png;." `
                   --hidden-import=customtkinter `
                   --hidden-import=tkinter `
                   --hidden-import=PIL `
                   --hidden-import=PIL._tkinter_finder `
                   --collect-all=customtkinter `
                   --clean `
                   reverse_pdf_gui.py
    
    - name: Create release package
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path "PDF页面顺序反转工具" -Force
        New-Item -ItemType Directory -Path "PDF页面顺序反转工具\程序" -Force
        Copy-Item "dist\PDF页面顺序反转工具.exe" -Destination "PDF页面顺序反转工具\程序\"
        Copy-Item "pdf_reverser.png" -Destination "PDF页面顺序反转工具\程序\"
        
        @"
        PDF页面顺序反转工具 v1.0

        功能说明：
        将PDF文件的页面顺序反转，从最后一页到第一页重新排序。

        使用方法：
        1. 运行 程序\PDF页面顺序反转工具.exe
        2. 点击"浏览"选择要处理的PDF文件
        3. 点击"开始转换"
        4. 等待处理完成

        注意事项：
        - 原文件不会被修改
        - 新文件会保存在原文件相同目录下
        - 新文件名格式：原文件名_reversed.pdf
        "@ | Out-File -FilePath "PDF页面顺序反转工具\使用说明.txt" -Encoding utf8
        
        Compress-Archive -Path "PDF页面顺序反转工具" -DestinationPath "PDF页面顺序反转工具.zip" -Force
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: PDF页面顺序反转工具
        path: PDF页面顺序反转工具.zip
    
    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: PDF页面顺序反转工具.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}