name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter==5.2.2
        pip install PyPDF2==3.0.1
        pip install pillow==10.2.0
        pip install pyinstaller==6.3.0
    
    - name: Create icon
      run: python pdf_icon.py
    
    - name: Build EXE
      run: |
        pyinstaller --name="PDF页面顺序反转工具" --windowed --onefile --icon=pdf_reverser.png --add-data="pdf_reverser.png;." --hidden-import=customtkinter --hidden-import=tkinter --hidden-import=PIL --collect-all=customtkinter reverse_pdf_gui.py
    
    - name: Create Release Package
      run: |
        mkdir PDF页面顺序反转工具
        copy dist\PDF页面顺序反转工具.exe PDF页面顺序反转工具\
        Compress-Archive -Path PDF页面顺序反转工具 -DestinationPath PDF页面顺序反转工具.zip
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF页面顺序反转工具
        path: PDF页面顺序反转工具.zip
    
    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: PDF页面顺序反转工具.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}